//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"

// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

namespace
{
// return the wxBORDER_SIMPLE that matches the current application theme
wxBorder get_border_simple_theme_aware_bit()
{
#if wxVERSION_NUMBER >= 3300 && defined(__WXMSW__)
    return wxSystemSettings::GetAppearance().IsDark() ? wxBORDER_SIMPLE : wxBORDER_STATIC;
#else
    return wxBORDER_DEFAULT;
#endif
} // DoGetBorderSimpleBit
bool bBitmapLoaded = false;
} // namespace

MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos,
                                       const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if(!bBitmapLoaded) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }

    wxBoxSizer* boxSizer1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1);

    m_mainPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    boxSizer1->Add(m_mainPanel, 1, wxEXPAND, WXC_FROM_DIP(5));

    wxBoxSizer* boxSizer11 = new wxBoxSizer(wxVERTICAL);
    m_mainPanel->SetSizer(boxSizer11);

    m_toolbar =
        new clToolBar(m_mainPanel, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), wxTB_FLAT);
    m_toolbar->SetToolBitmapSize(wxSize(16, 16));

    boxSizer11->Add(m_toolbar, 0, wxEXPAND, WXC_FROM_DIP(5));

    m_toolbar->AddTool(wxID_OPEN, _("Open"), wxXmlResource::Get()->LoadBitmap(wxT("16-folder-open-regular@2x")),
                       wxNullBitmap, wxITEM_DROPDOWN, wxT(""), wxT(""), NULL);

    m_toolbar->AddTool(wxID_NEW, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("16-mime-txt@2x")), wxNullBitmap,
                       wxITEM_NORMAL, wxT(""), wxT(""), NULL);

    m_toolbar->AddStretchableSpace();

    m_toolbar->AddSeparator();

    m_toolbar->AddTool(wxID_BOOKMARK, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("16-bookmark-yellow@2x")),
                       wxNullBitmap, wxITEM_CHECK, wxT(""), wxT(""), NULL);

    m_toolbar->AddTool(wxID_COLOURS, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("16-colour-pallette@2x")),
                       wxNullBitmap, wxITEM_CHECK, wxT(""), wxT(""), NULL);

    m_toolbar->AddTool(wxID_ANY, _("Another Tool"), wxXmlResource::Get()->LoadBitmap(wxT("16-file-regular@2x")),
                       wxNullBitmap, wxITEM_CHECK, wxT(""), wxT(""), NULL);
    m_toolbar->Realize();

    m_panelControls =
        new wxPanel(m_mainPanel, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    boxSizer11->Add(m_panelControls, 1, wxEXPAND, WXC_FROM_DIP(5));

    wxBoxSizer* boxSizer71 = new wxBoxSizer(wxHORIZONTAL);
    m_panelControls->SetSizer(boxSizer71);

    m_sidebar = new clSideBarCtrl(m_panelControls, wxID_ANY, wxDefaultPosition,
                                  wxDLG_UNIT(m_panelControls, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    boxSizer71->Add(m_sidebar, 0, 0, WXC_FROM_DIP(5));

    m_dataView = new clDataViewListCtrl(m_panelControls, wxID_ANY, wxDefaultPosition,
                                        wxDLG_UNIT(m_panelControls, wxSize(-1, 300)), wxDV_ROW_LINES | wxDV_SINGLE);

    boxSizer71->Add(m_dataView, 1, wxEXPAND, WXC_FROM_DIP(1));

    m_dataView->AppendIconTextColumn(_("Path"), wxDATAVIEW_CELL_INERT, WXC_FROM_DIP(-2), wxALIGN_LEFT,
                                     wxDATAVIEW_COL_RESIZABLE);
    m_dataView->AppendTextColumn(_("Is file?"), wxDATAVIEW_CELL_INERT, WXC_FROM_DIP(-2), wxALIGN_LEFT,
                                 wxDATAVIEW_COL_RESIZABLE);
    m_dataView->AppendTextColumn(_("File size"), wxDATAVIEW_CELL_INERT, WXC_FROM_DIP(-2), wxALIGN_LEFT,
                                 wxDATAVIEW_COL_RESIZABLE);
    wxBoxSizer* boxSizer133 = new wxBoxSizer(wxVERTICAL);

    boxSizer11->Add(boxSizer133, 0, wxEXPAND, WXC_FROM_DIP(5));

    m_panelButtons =
        new wxPanel(m_mainPanel, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_mainPanel, wxSize(-1, -1)), wxTAB_TRAVERSAL);

    boxSizer133->Add(m_panelButtons, 1, wxEXPAND, WXC_FROM_DIP(5));

    wxBoxSizer* boxSizer137 = new wxBoxSizer(wxVERTICAL);
    m_panelButtons->SetSizer(boxSizer137);

    wxFlexGridSizer* flexGridSizer141 = new wxFlexGridSizer(0, 2, 0, 0);
    flexGridSizer141->SetFlexibleDirection(wxBOTH);
    flexGridSizer141->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    flexGridSizer141->AddGrowableCol(1);

    boxSizer137->Add(flexGridSizer141, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_buttonOne = new clButton(m_panelButtons, wxID_ANY, _("Close the Folder"), wxDefaultPosition,
                               wxDLG_UNIT(m_panelButtons, wxSize(150, -1)), 0);
    m_buttonOne->SetToolTip(_("Close the Folder"));

    flexGridSizer141->Add(m_buttonOne, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_buttonTwo = new clButton(m_panelButtons, wxID_ANY, _("Button Two Clicker"), wxDefaultPosition,
                               wxDLG_UNIT(m_panelButtons, wxSize(-1, -1)), 0);

    flexGridSizer141->Add(m_buttonTwo, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_buttonDisabled = new clButton(m_panelButtons, wxID_ANY, _("Disabled"), wxDefaultPosition,
                                    wxDLG_UNIT(m_panelButtons, wxSize(-1, -1)), 0);
    m_buttonDisabled->Enable(false);

    flexGridSizer141->Add(m_buttonDisabled, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    wxArrayString m_choiceArr;
    m_choiceArr.Add(_("Item Number One"));
    m_choiceArr.Add(_("Item Number Two"));
    m_choiceArr.Add(_("Item Number Three"));
    m_choiceArr.Add(_("Item Number Four"));
    m_choice = new clChoice(m_panelButtons, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelButtons, wxSize(200, -1)),
                            m_choiceArr, 0);
    m_choice->SetSelection(0);

    flexGridSizer141->Add(m_choice, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    wxArrayString m_comboBoxArr;
    m_comboBoxArr.Add(_("Choice 1"));
    m_comboBoxArr.Add(_("Choice 2"));
    m_comboBoxArr.Add(_("Choice 3"));
    m_comboBoxArr.Add(_("Choice 4"));
    m_comboBoxArr.Add(_("Choice 5"));
    m_comboBoxArr.Add(_("Choice 6"));
    m_comboBoxArr.Add(_("Choice 7"));
    m_comboBox = new clComboBox(m_panelButtons, wxID_ANY, wxT(""), wxDefaultPosition,
                                wxDLG_UNIT(m_panelButtons, wxSize(-1, -1)), m_comboBoxArr, 0);
#if wxVERSION_NUMBER >= 3000
    m_comboBox->SetHint(wxT(""));
#endif
    m_comboBox->SetSelection(0);

    flexGridSizer141->Add(m_comboBox, 0, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_buttonAction = new clButton(m_panelButtons, wxID_ANY, _("My Button"), wxDefaultPosition,
                                  wxDLG_UNIT(m_panelButtons, wxSize(-1, -1)), 0);

    boxSizer137->Add(m_buttonAction, 1, wxALL | wxEXPAND, WXC_FROM_DIP(5));

    m_textCtrlLog = new wxTextCtrl(m_mainPanel, wxID_ANY, wxT(""), wxDefaultPosition,
                                   wxDLG_UNIT(m_mainPanel, wxSize(-1, 100)), wxTE_RICH | wxTE_MULTILINE);

    boxSizer11->Add(m_textCtrlLog, 0, wxEXPAND, WXC_FROM_DIP(1));

    m_myMenuBar = new wxMenuBar(0);
    this->SetMenuBar(m_myMenuBar);

    menu_clTreeCtrl = new wxMenu();
    m_myMenuBar->Append(menu_clTreeCtrl, _("clTreeCtrl"));

    m_menuItem13 = new wxMenuItem(menu_clTreeCtrl, ID_OPEN_FOLDER, _("Open folder..."), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItem13);

    menu_clTreeCtrl->AppendSeparator();

    m_menuItemExpandAll = new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("Expand All"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemExpandAll);

    m_menuItemCollapseAll = new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("Collapse All"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemCollapseAll);

    m_menuItemFirstVisible =
        new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("First Visible Item\tShift-F4"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemFirstVisible);

    m_menuItemNextVisibleItem =
        new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("Next Visible Item\tF4"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemNextVisibleItem);

    m_menuItemEnsureVisible =
        new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("Ensure Item Visible"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemEnsureVisible);

    m_menuItemSelectChildren =
        new wxMenuItem(menu_clTreeCtrl, ID_SELECT_CHILDREN, _("Select Children"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemSelectChildren);

    m_menuItemNextSibling =
        new wxMenuItem(menu_clTreeCtrl, ID_NEXT_SIBLING, _("Next Sibling\tF2"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemNextSibling);

    m_menuItemPrevSibling =
        new wxMenuItem(menu_clTreeCtrl, ID_PREV_SIBLING, _("Prev Sibling\tShift-F2"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemPrevSibling);

    m_menuItemDeleteAllItems = new wxMenuItem(menu_clTreeCtrl, wxID_ANY, _("Delete All Items"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemDeleteAllItems);

    menu_clTreeCtrl->AppendSeparator();

    m_menuItemFind = new wxMenuItem(menu_clTreeCtrl, wxID_FIND, _("Find Item...\tCtrl-F"), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemFind);

    m_menuItemSetWidth =
        new wxMenuItem(menu_clTreeCtrl, wxID_SET_TREE_COL_WIDTH, _("Set Column WIdth..."), wxT(""), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemSetWidth);

    menu_clTreeCtrl->AppendSeparator();

    m_menuItemExit = new wxMenuItem(menu_clTreeCtrl, wxID_EXIT, _("Exit\tAlt-X"), _("Quit"), wxITEM_NORMAL);
    menu_clTreeCtrl->Append(m_menuItemExit);

    menu_clDataViewListCtrl = new wxMenu();
    m_myMenuBar->Append(menu_clDataViewListCtrl, _("clDataViewListCtrl"));

    m_menuItem83 = new wxMenuItem(menu_clDataViewListCtrl, ID_DV_OPEN_FOLDER, _("Open folder"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem83);

    m_menuItem87 = new wxMenuItem(menu_clDataViewListCtrl, ID_FILL_WITH_5000_ENTRIES,
                                  _("Create view with 10,000 items"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem87);

    m_menuItem89 =
        new wxMenuItem(menu_clDataViewListCtrl, ID_DV_DELETE_ALL_ITEMS, _("Delete All Items"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem89);

    menu_clDataViewListCtrl->AppendSeparator();

    m_menuItem147 = new wxMenuItem(menu_clDataViewListCtrl, wxID_UP, _("Line Up"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem147);

    m_menuItem149 = new wxMenuItem(menu_clDataViewListCtrl, wxID_DOWN, _("Line Down"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem149);

    m_menuItem151 = new wxMenuItem(menu_clDataViewListCtrl, ID_PG_UP, _("Page Up"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem151);

    m_menuItem153 = new wxMenuItem(menu_clDataViewListCtrl, ID_PG_DOWN, _("Page Down"), wxT(""), wxITEM_NORMAL);
    menu_clDataViewListCtrl->Append(m_menuItem153);

    menu_Style = new wxMenu();
    m_myMenuBar->Append(menu_Style, _("Style"));

    m_menuItemZebra = new wxMenuItem(menu_Style, ID_ZEBRA, _("Zebra Colouring..."), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemZebra);
    m_menuItemZebra->Check();

    m_menuItemThemes = new wxMenuItem(menu_Style, ID_TOGGLE_THEMES, _("Toggle Themes"), wxT(""), wxITEM_NORMAL);
    menu_Style->Append(m_menuItemThemes);

    m_menuItemHideRoot = new wxMenuItem(menu_Style, ID_HIDE_ROOT, _("Hide Root"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemHideRoot);

    menu_Style->AppendSeparator();

    m_menuItemSingleSelection =
        new wxMenuItem(menu_Style, ID_SINGLE_SELECTION, _("Single Selection Tree"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemSingleSelection);
    m_menuItemSingleSelection->Check();

    m_menuItemShowSBOnFocus =
        new wxMenuItem(menu_Style, ID_SHOW_SB_ON_FOCUS, _("Show Scrollbar when focused Only"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemShowSBOnFocus);

    m_menuItemHideHeaders = new wxMenuItem(menu_Style, wxID_ANY, _("Hide Header"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemHideHeaders);

    m_menuItemNativeHeader =
        new wxMenuItem(menu_Style, ID_NATIVE_HEADER, _("Use Native Drawings"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemNativeHeader);

    m_menuItemSupportSearch = new wxMenuItem(menu_Style, wxID_ANY, _("Enable Search"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItemSupportSearch);

    m_menuItem155 = new wxMenuItem(menu_Style, ID_NEVER_SHOW_SCROLLBARS, _("Hide Scroll Bars"), wxT(""), wxITEM_CHECK);
    menu_Style->Append(m_menuItem155);

    m_menu163 = new wxMenu();
    m_myMenuBar->Append(m_menu163, _("Caption Bar"));

    m_menuItem165 = new wxMenuItem(m_menu163, wxID_ANY, _("Show action button"), wxT(""), wxITEM_CHECK);
    m_menu163->Append(m_menuItem165);

    m_menu163->AppendSeparator();

    m_menuItem167 = new wxMenuItem(m_menu163, wxID_ANY, _("Show Close Button"), wxT(""), wxITEM_CHECK);
    m_menu163->Append(m_menuItem167);
    m_menuItem167->Check();

    m_menuItem169 = new wxMenuItem(m_menu163, wxID_ANY, _("Show Maximize Button"), wxT(""), wxITEM_CHECK);
    m_menu163->Append(m_menuItem169);
    m_menuItem169->Check();

    m_menuItem171 = new wxMenuItem(m_menu163, wxID_ANY, _("Show Minimize Button"), wxT(""), wxITEM_CHECK);
    m_menu163->Append(m_menuItem171);
    m_menuItem171->Check();

    SetName(wxT("MainFrameBaseClass"));
    SetSize(wxDLG_UNIT(this, wxSize(-1, -1)));
    if(GetSizer()) {
        GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
    // Connect events
    this->Bind(wxEVT_UPDATE_UI, &MainFrameBaseClass::OnColoursUI, this, wxID_COLOURS);
    m_buttonOne->Bind(wxEVT_UPDATE_UI, &MainFrameBaseClass::OnCloseFolderUI, this);
    m_buttonOne->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &MainFrameBaseClass::OnButtonCloseFolder, this);
    m_buttonTwo->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &MainFrameBaseClass::OnButtonClicked, this);
    m_choice->Bind(wxEVT_COMMAND_CHOICE_SELECTED, &MainFrameBaseClass::OnChoice, this);
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnOpenFolder, this, m_menuItem13->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnExpandAll, this, m_menuItemExpandAll->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCollapseAll, this, m_menuItemCollapseAll->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnFirstVisible, this, m_menuItemFirstVisible->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNextVisible, this,
               m_menuItemNextVisibleItem->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnEnsureItemVisible, this,
               m_menuItemEnsureVisible->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSelectChildren, this,
               m_menuItemSelectChildren->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNextSibling, this, m_menuItemNextSibling->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPrevSibling, this, m_menuItemPrevSibling->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDeleteAllItems, this,
               m_menuItemDeleteAllItems->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnTreeFind, this, m_menuItemFind->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSetTreeColWidth, this, m_menuItemSetWidth->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnExit, this, m_menuItemExit->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDVOpenFolder, this, m_menuItem83->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnFillWith500Entries, this, m_menuItem87->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDVDeleteAllItems, this, m_menuItem89->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnLineUp, this, m_menuItem147->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnLineDown, this, m_menuItem149->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPgUp, this, m_menuItem151->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPgDown, this, m_menuItem153->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnZebraColouring, this, m_menuItemZebra->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnToggleTheme, this, m_menuItemThemes->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideRoot, this, m_menuItemHideRoot->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSingleSelection, this,
               m_menuItemSingleSelection->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowSBOnFocus, this,
               m_menuItemShowSBOnFocus->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideHeaders, this, m_menuItemHideHeaders->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNativeHeader, this, m_menuItemNativeHeader->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnMenuitemsupportsearchMenuSelected, this,
               m_menuItemSupportSearch->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideScrollbars, this, m_menuItem155->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCaptionBarToggleMenuButton, this,
               m_menuItem165->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCaptionBarToggleCloseButton, this,
               m_menuItem167->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowMaximizeButton, this, m_menuItem169->GetId());
    this->Bind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowMinimizeButton, this, m_menuItem171->GetId());
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Unbind(wxEVT_UPDATE_UI, &MainFrameBaseClass::OnColoursUI, this, wxID_COLOURS);
    m_buttonOne->Unbind(wxEVT_UPDATE_UI, &MainFrameBaseClass::OnCloseFolderUI, this);
    m_buttonOne->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &MainFrameBaseClass::OnButtonCloseFolder, this);
    m_buttonTwo->Unbind(wxEVT_COMMAND_BUTTON_CLICKED, &MainFrameBaseClass::OnButtonClicked, this);
    m_choice->Unbind(wxEVT_COMMAND_CHOICE_SELECTED, &MainFrameBaseClass::OnChoice, this);
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnOpenFolder, this, m_menuItem13->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnExpandAll, this, m_menuItemExpandAll->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCollapseAll, this, m_menuItemCollapseAll->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnFirstVisible, this,
                 m_menuItemFirstVisible->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNextVisible, this,
                 m_menuItemNextVisibleItem->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnEnsureItemVisible, this,
                 m_menuItemEnsureVisible->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSelectChildren, this,
                 m_menuItemSelectChildren->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNextSibling, this, m_menuItemNextSibling->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPrevSibling, this, m_menuItemPrevSibling->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDeleteAllItems, this,
                 m_menuItemDeleteAllItems->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnTreeFind, this, m_menuItemFind->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSetTreeColWidth, this,
                 m_menuItemSetWidth->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnExit, this, m_menuItemExit->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDVOpenFolder, this, m_menuItem83->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnFillWith500Entries, this, m_menuItem87->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnDVDeleteAllItems, this, m_menuItem89->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnLineUp, this, m_menuItem147->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnLineDown, this, m_menuItem149->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPgUp, this, m_menuItem151->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnPgDown, this, m_menuItem153->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnZebraColouring, this, m_menuItemZebra->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnToggleTheme, this, m_menuItemThemes->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideRoot, this, m_menuItemHideRoot->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnSingleSelection, this,
                 m_menuItemSingleSelection->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowSBOnFocus, this,
                 m_menuItemShowSBOnFocus->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideHeaders, this, m_menuItemHideHeaders->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnNativeHeader, this,
                 m_menuItemNativeHeader->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnMenuitemsupportsearchMenuSelected, this,
                 m_menuItemSupportSearch->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnHideScrollbars, this, m_menuItem155->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCaptionBarToggleMenuButton, this,
                 m_menuItem165->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnCaptionBarToggleCloseButton, this,
                 m_menuItem167->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowMaximizeButton, this, m_menuItem169->GetId());
    this->Unbind(wxEVT_COMMAND_MENU_SELECTED, &MainFrameBaseClass::OnShowMinimizeButton, this, m_menuItem171->GetId());
}

MyImages::MyImages()
    : wxImageList(16, 16, true)
    , m_imagesWidth(16)
    , m_imagesHeight(16)
{
    if(!bBitmapLoaded) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }

    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("folder"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("folder"), bmp));
        }
    }
    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("folder@2x"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("folder@2x"), bmp));
        }
    }

    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("folder_open"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("folder_open"), bmp));
        }
    }
    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("folder_open@2x"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("folder_open@2x"), bmp));
        }
    }

    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("file"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("file"), bmp));
        }
    }

    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("logo"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("logo"), bmp));
        }
    }

    {
        wxBitmap bmp;
        wxIcon icn;
        bmp = wxXmlResource::Get()->LoadBitmap(wxT("colours"));
        if(bmp.IsOk()) {
            if((m_imagesWidth == bmp.GetWidth()) && (m_imagesHeight == bmp.GetHeight())) {
                icn.CopyFromBitmap(bmp);
                this->Add(icn);
            }
            m_bitmaps.insert(std::make_pair(wxT("colours"), bmp));
        }
    }
}

MyImages::~MyImages() {}
